### ISSUE TITLE
Tilt Data unable to be edited

### ISSUE THREAD

**Issue by mongatronanoid** [rlightner/public-BrewStatus#21]
Hi,
I am trying to remove several data points from a brew and I can edit the data - but it doesn't save.

**Comment by mongatronanoid** [comment]
Hi - Since logging this ticket I am now unable to access any of my Brews. It just generates a crash report.

**Comment by mongatronanoid** [comment]
Any update on this - I am totally unable to use the brewstat website to access any of my current or last breed I just get a crash report. 
This is getting incredibly frustrating

**Comment by rlightner** [comment]
Sorry about that, I've been out of the country with no internet access and just got back a few hours ago. Looks like some data got edited on a tilt that was causing some averaging issues. I've corrected the offending area and you should see your dashboard now. I'll look into the editing portion of the Tilt.

**Comment by mongatronanoid** [comment]
No worries at all.

Thanks for fixing the login issue.

I am still unable to edit the tilt data. Not something I plan on doing a lot of. Just the current brew seems to have got a crazy reading. (Tim - IPA)

I am also unable to open Galaxy Ale III  or Bitter without it crashing.

Regards,

Simon.

Sent from my iPhone

On 2 Mar 2017, at 1:08 am, Raine Lightner <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry about that, I've been out of the country with no internet access and just got back a few hours ago. Looks like some data got edited on a tilt that was causing some averaging issues. I've corrected the offending area and you should see your dashboard now. I'll look into the editing portion of the Tilt.

**Comment by rlightner** [comment]
I've fixed those two brews and the strange reading on Tim. I need to redo the editing data, it was released too soon.

**Comment by mongatronanoid** [comment]
Cheers.


Looks perfect.


Thanks,


Simon.


________________________________
